name: Marketing Crawler

on:
  schedule:
    # 매일 오전 9시(UTC+9 기준으로는 0시)에 실행
    - cron: '0 0 * * *'
  # 수동 실행 가능하도록 설정
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment
      run: |
        mkdir -p logs
        mkdir -p screenshots
      
    - name: Set up Google service account
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > naver-452205-a733573ea425.json
        
    - name: Run Naver Ads Crawler
      run: python crawl_naver_ads.py
      
    - name: Run Google Ads Crawler
      run: python crawl_google_ads.py
      
    - name: Run Meta Ads Crawler
      run: python crawl_meta_ads.py
      
    - name: Run Summary Generator
      run: python summary.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
