name: Send Email

on:
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Send email notifications
        run: python mail.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
