name: Web Crawler and Notifier

on:
  schedule:
    - cron: '0 1 * * *'   # 매일 UTC 1시(한국 시간 10시)에 실행
    - cron: '0 5 * * *'   # 매일 UTC 5시(한국 시간 14시)에 실행
    - cron: '0 7 * * *'   # 매일 UTC 7시(한국 시간 16시)에 실행
    - cron: '0 9 * * *'   # 매일 UTC 9시(한국 시간 18시)에 실행
  workflow_dispatch:      # 수동 실행 옵션

jobs:
  crawl_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create service account key file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > naver-452205-a733573ea425.json

      # 크롤링 스크립트 실행
      - name: Run Naver Ads crawler
        run: python crawl_naver_ads.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

      - name: Run Google Ads crawler
        run: python crawl_google_ads.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

      - name: Run Meta Ads crawler
        run: python crawl_meta_ads.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

      - name: Run BOSS PDF crawler
        run: python crawl_boss_pdf.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # 요약 스크립트 실행
      - name: Generate summaries
        run: python summary.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
